### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by GaoMia** [RyanXingQL/PowerQE#7]
I can't find the config file for train_cfg and test_cfg. Who can help me find the files

**Comment by ryanxingql** [comment]
Hi. One example for training the AR-CNN:

```bash
conda activate powerqe &&\
 CUDA_VISIBLE_DEVICES=0\
 PORT=29500\
 tools/dist_train.sh\
 configs/arcnn/div2k.py\
 1
```

where the config file is located at `configs/arcnn/div2k.py`.

You use the same config file for testing AR-CNN.
